### ISSUE TITLE
Gnuplot in MacOS

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#11]
The default setting fails to use gnuplot. An attempt to generate a gnuplot graph has effect, nor error. The error is fixed by changing the options for Gnuplot in the Analysis of Result window indicating "Terminal" instead of "xterm" for the system terminal.

**Comment by MCP1** [comment]
Hi Marco.
Cannot reproduce your problem. The default System Terminal in macOS is already set to Terminal, you shouldn't have to change this. Please check in your LMM Options if you don't have the System Terminal set to xterm.

**Comment by marcov64** [comment]
Hi,
You are right, I need to set Terminal as "System Terminal" option in LMM and this option is inherited by the Lsd Model Program. I can't say why it was set to "xterm". Ideally there should be a control and/or a warning, but I guess it is such a rare occurrence that we can leave as it is.

**Comment by MCP1** [comment]
It was set to xterm as it was the (very) old default (from the time mac came with X11...). As you probably never reloaded the default settings and had xterm installed, it kept working. Better this way!
