### ISSUE TITLE
Marking Debug variables

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#13]
During a debugging session it is possible to add a new variable to be debugged. It is possible to add the flag to a single instance or to all the instances of that variable. However it is not possible to remove the flag to all instances at once. This is annoying when you set many variables to be debugged. 
Low priority, but should be fixed at the first opportunity

**Comment by MCP1** [comment]
Fixed. To remove the debug flag from all instances, check and uncheck the Debug all checkbox.
