### ISSUE TITLE
Bug in Lattice

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#15]
The INIT_LAT command can cause a crash. If you have a model with a rectangular lattice defined where the number of columns exceeds the number of rows, for example: INIT_LAT(1000,2,5 ), than you may successfully run the model once online, but if you then reload it and run it again, it crashes. 

The alternative ( INIT_LAT(1000,5,2 ); ) does not cause any problems.

For testing: Just create an empty model with a single equation that initialises the lattice in the above way at t==1.

**Comment by MCP1** [comment]
Thanks for the report Frederik.
It should be fixed now.
