### ISSUE TITLE
win32 gnuplot error 1 - info message 

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#20]
Using the win32 version, the cross-section xy plot does not work on machines that do not have gnuplot installed.

A proper message that installation of gnuplot for such plots is necessary would be fine (and I think this is the issue?) - the readme explains this, but still this would be a good position for an info.

**Comment by MCP1** [comment]
That is correct, Gnuplot has to be installed by the user in all platforms, as indicated in Readme.txt.
I just improved the error messages to take that in consideration.
Thanks for the report!
