### ISSUE TITLE
Error in LMM scripts: ADDNOBJ

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#33]
In LMM the script to add new objects fails to accept a v[XXX] as number of new objects. That is, inserting the values for the following line the scripts works properly:
 cur = ADDNOBJ("Agent", 33);

The script fails instead to work trying to insert:
cur = ADDNOBJ("Agent", v[33]);

This happens in the MacOS version, release 7.1 Jan. 4 2019

**Comment by MCP1** [comment]
Fixed, please test!
