### ISSUE TITLE
Erratic click response in LSD browser on macOS

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#34]
In MacOS the LSD model program windows responds erratically to mouse clicks. Every supposedly active element such as object labels, element label, parent name cannot be activated with the mouse click. 
Strangely they become active, and only once, if the mouse click is applied on the graphical model structure window. After a click there the main Lsd browser window reacts correctly to the mouse click, but only once. After that it returns passive.

**Comment by marcov64** [comment]
High Sierra

Il giorno Mar 22 Gen 2019, 06:27 Marcelo Pereira <notifications@github.com>
ha scritto:

**Comment by MCP1** [comment]
I also tested in one real mac using High Sierra and the bug doesn't show...
Are you sure you are not using any legacy configuration? Current version DOES NOT uses XQuartz/X11 and LMM DOES NOT need to be recompiled.
It seems this is machine specific, as well the form the bug shows. Maybe it was introduced by the significant changes introduced in Tk to support macOS Mojave.
I don't have the resources to track this bug further, if you could try to take a deep look it would be highly appreciated.

**Comment by MCP1** [comment]
Should be fixed now
