### ISSUE TITLE
write lattice : Bug & suggested fix (check input)

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#35]
In `update_lattice( double line, double col, double val )` in util.cpp the input is checked without converting it to double first, although the writing converts the double to int. I suggest do change the check to be in line with the operation. I.e.

`if ( line <= 0 || col <= 0 || (int) line > rows || (int) col > columns || fabs( val ) > INT_MAX )`

**Comment by FrederikSchaff** [comment]
And I have one other suggestion for a major speed improvement. Check if the colour in the lattice will be changed befor kicking the updating process.

You may take a look at the recent changes in [https://github.com/marcov64/Lsd/tree/GIS-beta/src](https://github.com/marcov64/Lsd/tree/GIS-beta/src), where I implemented it as follows.

`// save lattice color data
	if ( lattice != NULL && rows > 0 && columns > 0 ){
        int y = (int) line - 1;
        int x = (int) col - 1;
        int color = max (0, floor (val) );
        if (color == lattice[y][x])
            return 0; //nothing needs doing
        else
            lattice[y][x] = color;
		//lattice[ ( int ) line - 1 ][ ( int ) col - 1 ] = ( int ) max( 0, floor( val ) );
    }`

**Comment by MCP1** [comment]
Thanks for the suggestions Frederik. Both were included in the last beta snapshot.
