### ISSUE TITLE
LSD-8.0-beta model compilation issue

### ISSUE THREAD

**Issue by fl0rianB** [marcov64/Lsd#40]
It seems there is an issue with the linux-installer: 
If I run LSD-8.0 from the extracted zip from github, LMM and LSD seems to work properly. 

But if I follow the instructions in the readme.txt file, #4.3 Linux installation,  lsd returns the following compilation error:
```
/usr/bin/ld: /home/Lsd-8.0-October3/src/common.o: in function `Tcl_discard_change(void*, Tcl_Interp*, int, char const**)':
common.cpp:(.text+0x5): undefined reference to `discard_change()'
collect2: error: ld returned 1 exit status
make: *** [makefile:43: LSD] Error 1
```
My system is an up to date debian 10.6. Libraries build-essential gdb gnuplot-qt multitail zlib1g-dev tcl-dev tk-devbuild-essential gdb gnuplot-qt multitail zlib1g-dev tcl-dev tk-dev are installed and I recompiled LMM.

**Comment by MCP1** [comment]
Hi fl0rianB. Thanks for the update.
The installation went fine, there is an object file which should be deleted after recompiling LMM to your distro. The installer normally does this after an automatic recompilation, but you have to do it manually after a manual compilation. I'll add a note to Readme.txt about this.
Please open LMM menu 'Model > Model Options' and click on the 'Clean Obj.' button, it should fix the error you got. Or use 'make -f makefile.linux clean' in the command line after recompiling LMM.
