### ISSUE TITLE
LSD-8.0-beta - Segmentation violation when changing initial values with right click

### ISSUE THREAD

**Issue by fl0rianB** [marcov64/Lsd#41]
I get a segmentation violation error when I try to change the initial value of a parameter of various example models. 
The models run with the original configuration without issue. It is only when I try to change initial values with right click - Initial values.  The error appears when I click on the Ok button. 
I get no error using the menu Data - Initial values. 

LSD.err shows: 
```
====================> NEW TCL SESSION

(10/05/20 10:03:59)
Command:
FATAL ERROR
Message:
System Signal received: SIGSEGV (Segmentation violation)
```

My system is an up to date debian 10.6. Libraries build-essential gdb gnuplot-qt multitail zlib1g-dev tcl-dev tk-devbuild-essential gdb gnuplot-qt multitail zlib1g-dev tcl-dev tk-dev are installed and I recompiled LMM.

**Comment by MCP1** [comment]
Hi fl0rianB.
Thanks for pointing the bug.
It seems Tk is working differently among platforms in some circumstances...
I did some changes that should prevent this problem. You can pull/download the most recent commit or simply replace the file set_all.cpp in folder src by the new version here:
https://github.com/marcov64/Lsd/blob/8.0-beta/src/set_all.cpp 
Best,
Marcelo.
