### ISSUE TITLE
Fail checking missing lags

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#42]
When the code includes a lagged variable but the model configuration assigns no lags to the variable the model generates random results (or possibly using the default value of zero). This is certainly an issue at t=1, though may not necessarily be problematic at the generic t. However, it needs to be fixed. Preferebly stopping the simulation with an error or, at very least, issuing a warning allowing the user to continue the simulation.
Ver. 8.0-beta-1

**Comment by MCP1** [comment]
Ciao Marco!
I'm not sure I understood how did you get this problem. To try to reproduce, I created a new model, created one equation (X(t)=X(t-1)+1), compiled-run, created variable X with lag=1, did NOT define an initial value, and tried to run the model. I immediately got an Error box ("Required initialization values missing") and the simulation stopped.
Are you sure you didn't open the Data>Initial Values window on the object containing the just created variable? As it always has been the case in LSD, when you open the initial values window, it fills all non-initialized elements to zero for you and, critically, marks all the values presented as initialized (to zero) even if you don't touch them. I once thought about changing this behavior, but was uncertain if this would cause even more confusion...

**Comment by marcov64** [comment]
Hi Marcelo,
Sorry, I was not clear. The issue emerges when you write an equation with a lag, i.e. you use X[t-1] in the code, but you declare the variable with 0 lags in the configuration. The simulation does not signal the error at the first time step, t=1, using 0 as the value for X[t-1], so it is a quite dangerous bug because creates wrong values. 

I send you the model, in case the error may depend on the structure, and the model I am working on is fairly complex. The error takes place in the computation for InterestEF that uses InterestRate[t-1]. However, the model defines InterestRate without lags, but the simulation runs without errors returning 0.   
The problem existed also in the previous version, the 7.2. I just switched to the 8.0 today.

**Comment by MCP1** [comment]
Thanks for the clarification.
Indeed, there was a bug introduced long time ago, when allowing using saved values on computations (USE_SAVED macro). 
It should be fixed by the last commit, let me know if it's not.
