### ISSUE TITLE
"Save as" not working on MacOS

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#44]
On MacOS 10.15.7 the "Save as" option in the LSD Browser does not work, the Finder windows offering for the name gets stuck when confirming the name. Bit strange, can't understand where the bug may be. Even the "Cancel" button does not work, turning the window in a ghost and not returning control to the main LSD browser. Got to kill the Browser and creating manually from Finder a new file.
Control-s, "Save", works fine.

**Comment by MCP1** [comment]
Hi Marco.
I couldn't reproduce the problem on my vMac (10.15.5). I open an existing model, compile-run it, load any configuration and save it under a different name (same folder). It worked flawlessly. It also works the same in Windows and Ubuntu. I have changed nothing about Save As in version 8.
Do you have any special Tcl/Tk configuration in your computer?  Is it working in version 7.x or an older one?
Thanks!
