### ISSUE TITLE
Installer creation issue with latest 8-0 beta

### ISSUE THREAD

**Issue by fl0rianB** [marcov64/Lsd#50]
Since the last update, I'm not able anymore to create the linux installer (on an up-to-date Debian testing). 
To reproduce the issue, extract Lsd-8.0-beta.zip, go into Lsd-8.0-beta/installer, run
`./create-installer-linux.sh`
installer/LSD-installer-linux-8-0-beta-3.sh is successfully created & LSD installer package created: /home/flo/Apps/Lsd-8.0-beta/installer/LSD-installer-linux-8-0-beta-3.zip
Extract the later, go in the folder LSD-installer-linux-8-0-beta-3 and run
`./LSD-installer-linux-8-0-beta-3.sh 
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing LSD Installer (8.0-beta-3)  100%  
Error in startup script: can't read "sysTerm": no such variable
    while executing
"llength $sysTerm "
    invoked from within
"if { $CurPlatform in [ list linux windows ] && [ llength $sysTerm ] < 2 } { \
	set sysTerm $DefaultSysTerm
}"
    (file "/tmp/selfgz30892/src/gui.tcl" line 193)
    invoked from within
"source "$RootLsd/$LsdSrc/gui.tcl""
    (file "./src/installer.tcl" line 62)
`

**Comment by MCP1** [comment]
Thanks for the heads up fl0rianB! Should be fixed now.
